### ISSUE TITLE
Create SimpleRegressorList class

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#14]
**Description of feature/enhancement**
Create a class to keep track of the top N best performing regression models on a certain data set.

**Description of implementation**
Users should be able to export a model at a certain index. This list should fine tune each algorithm's hyper-parameters to be the most accurate and keep track of values such as model accuracy and latency.

**Why this is a good feature/enhancement**
This will allow users to pick and choose algorithms based on personal preference. 

**Additional context**
Model attributes should be as descriptive as possible.

**Comment by sh-biswas** [comment]
Hi @skekre98, I'd like to take a look at this issue and possibly #24 and see what I can do. I've taken a look at the SimpleClassifierList class as well as the discussion in #38 and would like to try implementing this class based on what I've seen if that works for you.

**Comment by skekre98** [comment]
@sh-biswas that would be great! Would you mind waiting till we close #38 to open a PR so we have a finalized version of `SimpleRegressor`? I'll go ahead and assign the issue over to you for track keeping.

**Comment by sh-biswas** [comment]
Yes, sounds good!

**Comment by skekre98** [comment]
@sh-biswas SimpleRegressor was merged in #38. Please take a look at it when working on this issue :)

**Comment by skekre98** [comment]
@sh-biswas any progress on this issue?

**Comment by sh-biswas** [comment]
@skekre98 sorry for my absence, university kept me quite busy this week. I will start this issue tonight and will let you know when I open a PR!

**Comment by skekre98** [comment]
@sh-biswas cool, no rush :)

**Comment by sh-biswas** [comment]
Hi @skekre98 quick question. I am modeling this class off of the SimpleClassifierList class, and I wanted to ask about the metrics map. What is the purpose of `scoring="auto"`? I noticed that training accuracy was mapped to it, so would there be similar code in the SimpleRegressorList class: `scoring="auto"` where training score in SimpleRegressor is mapped to "auto"?

**Comment by skekre98** [comment]
Hi, @sh-biswas, since regression problems can't be validated the same way as classification we have used separate "scoring" metrics for SimpleRegressor:
https://github.com/skekre98/simple_learn/blob/aac7417cc01208c6d996c216ff926c6261d1a7b1/simple_learn/regressors/simple_regressor.py#L151-L159

We should still have a mechanism like `scoring="auto"`, but let's perhaps map this to one of the metrics used in SimpleRegressor. A good approach for SimpleRegressorList would be to have a similar class structure to SimpleClassifierList, but keep the implementation similar to SimpleRegressor.

**Comment by sh-biswas** [comment]
Okay, perfect thank you! Yes, I was planning on mapping it to the metric "Training score" in SimpleRegressor

**Comment by skekre98** [comment]
Closed in #60
