### ISSUE TITLE
Add unique test cases to SimpleClassifier

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#29]
**Description of feature/enhancement**
Currently `SimpleClassifier` is only being tested against two different datasets, wine and iris. It would be a good idea to verify this class against more datasets.  

**Description of implementation**
Add the test cases to the `TestSimpleClassifier` class:
https://github.com/skekre98/simple_learn/blob/953150faecf12951407e2aed3418fd139b0ab9ed/tests/classifiers/simple_classifier_tests.py#L33

Recommended to use pre-wrangled datasets such as those available in `sklearn`.

**Why this is a good feature/enhancement**
Will allow us to verify the class against a wider variety of datasets.

**Additional context**
In the future might be nice to create in house datasets for testing.

**Comment by sh-biswas** [comment]
Hello,

I'm a new open-source contributor, and I recently came across this project and found it very interesting! I would like to help out by contributing some tests for this particular issue. I've added tests for the new datasets referenced in pull request #37 and am currently looking for more sklearn datasets to use for testing.

I do have one question: I've noticed that there are a few issues regarding documentation. Should I add documentation for the tests?

**Comment by skekre98** [comment]
Hi @sh-biswas, that would be great! I'll go ahead and assign the issue over to you.
 
> I do have one question: I've noticed that there are a few issues regarding documentation. Should I add documentation for the tests?

Yes, that would be much appreciated.
