### ISSUE TITLE
Add export method to SimpleClassifier class

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#35]
**Description of feature/enhancement**
We will need a way to export the sklearn model so users have the ability to save them for future use. 
Ex.
```python
clf = SimpleClassifier()
clf.fit(X,y)
clf.export() # saves the sklearn model
```

**Description of implementation**
I recommend using the `joblib` library, but any ideas are welcome. I also recommend having an input parameter called _name_ in case the user wishes to save the model with a unique name.

Ex.
```python
def export(self, name="classifier"):
    pass
```

**Why this is a good feature/enhancement**
This will allow users to persist models without having to retrain them for future use.

**Additional context**
n/a

**Comment by Redbullrish** [comment]
Where would this method be?

**Comment by skekre98** [comment]
> Where would this method be?

https://github.com/skekre98/simple_learn/blob/main/simple_learn/classifiers/simple_classifier.py

**Comment by mavismonica** [comment]
I installed simple-learn. I am able to import simple_learn. But while importing model_param_map' using 'from simple_learn.classifiers.param_grid import model_param_map', getting the error " ModuleNotFoundError: No module named 'simple_learn.classifiers' ".

**Comment by skekre98** [comment]
> I installed simple-learn. I am able to import simple_learn. But while importing model_param_map' using 'from simple_learn.classifiers.param_grid import model_param_map', getting the error " ModuleNotFoundError: No module named 'simple_learn.classifiers' ".

Do you mean `ModuleNotFoundError: No module named simple_learn.classifiers.param_grid`?  If so, this is correct, `param_grid` currently is not being imported into the classifier module init file:
https://github.com/skekre98/simple_learn/blob/d8b71f004d452c258a44a0c979846d446cd27218/simple_learn/classifiers/__init__.py#L21-L25
I can't really think of a reason that the user would need the `model_param_map` since it is only being used in the grid search. Did you have one in mind?

**Comment by mavismonica** [comment]
> > I installed simple-learn. I am able to import simple_learn. But while importing model_param_map' using 'from simple_learn.classifiers.param_grid import model_param_map', getting the error " ModuleNotFoundError: No module named 'simple_learn.classifiers' ".
> 
> Do you mean `ModuleNotFoundError: No module named simple_learn.classifiers.param_grid`? If so, this is correct, `param_grid` currently is not being imported into the classifier module init file:
> https://github.com/skekre98/simple_learn/blob/d8b71f004d452c258a44a0c979846d446cd27218/simple_learn/classifiers/__init__.py#L21-L25
> 
> 
> I can't really think of a reason that the user would need the `model_param_map` since it is only being used in the grid search. Did you have one in mind?

I am actually having the error while doing 
`from simple_learn.classifiers import SimpleClassifier`
Here is the traceback : 
![image](https://user-images.githubusercontent.com/61350590/103292189-a046bf80-49ed-11eb-902c-a73b948d5a13.png)

**Comment by skekre98** [comment]
@mavismonica I am unfortunately unable to recreate this issue. From the log I can see that you are importing `param_grid` in your python file which will indeed throw an error since it is not present in the `__init__` file of the module.
 
However this won't be an issue when calling `SimpleClassifier`:
```python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> from simple_learn.classifiers.param_grid import model_param_grid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'model_param_grid' from 'simple_learn.classifiers.param_grid' (/Users/sharvil.kekre/projects/simple_learn/simple_learn/classifiers/param_grid.py)
```

If you have any further questions regarding the matter, please feel free to open up an issue regarding it on a separate thread :)

**Comment by skekre98** [comment]
Rather than save the sklearn model, it might be better to create save workflow for the entire SimpleModel
