### ISSUE TITLE
Issues with logging SimpleObjects to terminal

### ISSUE THREAD

**Issue by Turtle24** [skekre98/simple_learn#48]
**Describe the bug**
TypeError: Object of type int32 is not JSON serializable when trying to fit the iris dataset with the SimpleClassier. 

**To Reproduce**
1. Go to 'python terminal'
2. Run 'attempt the demo from the ReadMe'

**Expected behavior**
Expected the SimpleClassifier to fit the Iris dataset.

**Screenshots**
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aidan\simple_learn\simple_learn\classifiers\simple_classifier.py", line 85, in __str__     
    return json.dumps(attr, indent=4)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps     
    return cls(
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 201, in encode     
    chunks = list(chunks)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable
>>>
'''

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: [e.g. 0.0.1]

**Additional context**
json.dumps() doesn't handle int32 and requires an int for the required output.

**Comment by Turtle24** [comment]
Here's the proposed fix for the TypeError. As mentioned in #39 I added the extra conversion handler in the simple_classifier and got the below results. 

It seems to give the desired result however the training duration is 0.0s which isn't ideal. I'm thinking that maybe the training duration is the root cause?

```
class npEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.int32):
            return int(obj)
        return json.JSONEncoder.default(self, obj)

class SimpleClassifier:
. . .

def __str__(self):
. . .
return json.dumps(attr, cls=npEncoder, indent=4)
```
Result:
```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> iris = load_iris()
>>> clf = SimpleClassifier()
>>> clf.fit(iris.data, iris.target)
>>> print(clf) 
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0s",
    "GridSearch Duration": "0.11002588272094727s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
>>> iris = load_iris()
>>> clf = SimpleClassifier()
>>> clf.fit(iris.data, iris.target)
>>> print(clf)
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0s",
    "GridSearch Duration": "0.11002588272094727s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```

**Comment by skekre98** [comment]
Great catch @Turtle24, would you be interested in taking up this issue?

 > It seems to give the desired result however the training duration is 0.0s which isn't ideal. I'm thinking that maybe the training duration is the root cause?

Based on `npEncoder` I don't think it would be making any changes to the training time since it is of type _float_. To clarify we are getting it directly from the [gridsearch](https://github.com/skekre98/simple_learn/blob/ac83490bde0f730367206623c3d835b9d24e3379/simple_learn/classifiers/simple_classifier.py#L129). Is it possible that the json encoder is truncating the training duration?

**Comment by skekre98** [comment]
Actually on the most recent version I was able to print the SimpleClassifier object without any problems:
```python
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>>
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>>
>>> clf = SimpleClassifier()
>>> clf
<simple_learn.classifiers.simple_classifier.SimpleClassifier object at 0x107a75dd0>
>>> clf.fit(iris.data, iris.target)
>>> print(clf)
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0007078647613525391s",
    "GridSearch Duration": "0.19384217262268066s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
>>> simple_learn.__version__
'0.0.18'
```

However there does seem to be an issue, the python terminal prints the memory location of the object rather than object info. Ideally we would like it to look like this:
```python
>>> clf
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0007078647613525391s",
    "GridSearch Duration": "0.19384217262268066s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```

**Comment by Turtle24** [comment]
Thanks @skekre98, I'll definitely take it on.

Ok awesome, I'll check it out and get back to you.

**Comment by Turtle24** [comment]
I was still getting the TypeError as seen below. It's because of the __str__ returning the json with an int32 still. However I may have found a fix for everything. I printed out the version aswell, so you can see I have the latest simple-learn.
```
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> clf
<simple_learn.classifiers.simple_classifier.SimpleClassifier object at 0x000001783B75F2E0>
>>> clf.fit(iris.data, iris.target)
>>> clf       
<simple_learn.classifiers.simple_classifier.SimpleClassifier object at 0x000001783B75F2E0>
>>> print(clf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aidan\simple_learn\simple_learn\classifiers\simple_classifier.py", line 83, in __str__
    return json.dumps(attr, indent=4)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable
>>> simple_learn.__version__
'0.0.18'
>>>
```
I created a module for the encoder fix so it looks a bit neater now, the class doesn't sit in the SimpleClassifier module. So you just import the encoder now and then the result variable holds the output. Using the variable stops the truncation, I'm not too sure why but I'll find out and update this comment.

```
from  simple_learn.encoder import encoder_fix
. . .
def __str__(self):
. . . 
result = json.dumps(attr, cls=encoder_fix.npEncoder, indent=4)
return result
```
Now you get the output as seen below:
```
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> clf
<simple_learn.classifiers.simple_classifier.SimpleClassifier object at 0x000001C51B6FF2E0>
>>> clf.fit(iris.data, iris.target)
>>> print(clf)
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0010001659393310547s",
    "GridSearch Duration": "0.09302067756652832s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```
Ok now for the desired result of not just seeing the objects pointer in memory. I added a __repr__ method that returns the object in the desired output. I added the elif statement otherwise the training duration gets truncated again. 

```
 def __repr__(self):
        if self.train_duration is None:
            pass
        elif self.train_duration is not None:
            self.train_duration = float(self.train_duration)
        return 'Type: {}\n, Training Duration: {}\n, GridSearch Duration: {}\n, Parameters {}\n,  Metrics: {}'.format(self.name, 
                                      self.train_duration, self.gridsearch_duration, self.attributes, self.metrics)
```

Now you get the desired output as seen below. The __str__ will return the json output when print is called and __repr__ returns the object in the new format.
```
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> clf
Type: Empty Model
, Training Duration: None  
, GridSearch Duration: None
, Parameters {}
,  Metrics: {}
>>> clf.fit(iris.data, iris.target)
>>> clf
Type: KNeighborsClassifier
, Training Duration: 0.0009999275207519531
, GridSearch Duration: 0.10402321815490723
, Parameters {'metric': 'euclidean', 'n_neighbors': 4, 'weights': 'uniform'}
,  Metrics: {'Training Accuracy': 0.9866666666666667, 'Jaccard Score': 0.9245283018867925, 'F1 Score': 0.96}
>>> print(clf) 
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009999275207519531s",
    "GridSearch Duration": "0.10402321815490723s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```

**Comment by skekre98** [comment]
Awesome work @Turtle24 🎉 , is there a way we can make the `__repr__` method return similar to the `__str__` return? It will likely be called in the SimpleClassifierList class' `__str__` and `__repr__` methods. I'll also go ahead and create a separate issue for the encoder to keep track of it.

**Comment by Turtle24** [comment]
Thanks @skekre98, I made their returns the same and there isn't any truncation issues either. I just made both the methods similar so when the ```__str__``` or ```__repr__``` method is called, you get the expected output.. 

Here's the code for the ```__str__``` and ```__repr__``` methods: Storing the json avoids the truncation as mentioned earlier and it's pretty much the same code so you get the same output for both methods. 

```
    def __str__(self):

        for k in self.attributes:
            if type(self.attributes[k]) == np.int64:
                self.attributes[k] = int(self.attributes[k])

        attr = {
            "Type": self.name,
            "Training Duration": "{}s".format(self.train_duration),
            "GridSearch Duration": "{}s".format(self.gridsearch_duration),
            "Parameters": self.attributes,
            "Metrics": self.metrics,
        }

        str_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
        return str_out

    def __repr__(self):
        
        attr = {
            "Type": self.name,
            "Training Duration": "{}s".format(self.train_duration),
            "GridSearch Duration": "{}s".format(self.gridsearch_duration),
            "Parameters": self.attributes,
            "Metrics": self.metrics,
        }
        
        repr_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
        return repr_out
```

Here's the output:

```
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> clf
{
    "Type": "Empty Model",
    "Training Duration": "Nones",  
    "GridSearch Duration": "Nones",
    "Parameters": {},
    "Metrics": {}
}
>>> clf.fit(iris.data, iris.target)
>>> clf
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009999275207519531s",
    "GridSearch Duration": "0.11702752113342285s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
>>> print(clf) 
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009999275207519531s",
    "GridSearch Duration": "0.11702752113342285s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```

**Comment by skekre98** [comment]
@Turtle24 Awesome work 🎉 , I think this looks good to merge. Can you add this usage to the SimpleModel classes and open a PR!
