### ISSUE TITLE
Add new __str__ and __repr__ method to other SimpleModels

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#52]
**Description of feature/enhancement**
New string and representation method was created that leverages the npEncoder. Add this implementation to all SimpleModel classes:
https://github.com/skekre98/simple_learn/blob/39f1674ebee90f2bc5df36b4c933a2021addeae4/simple_learn/encoders/simple_model_encoder.py#L26-L30

**Description of implementation**
Implementation will essentially be the same as in SimpleClassifier:
```python
def __str__(self):

    for k in self.attributes:
        if type(self.attributes[k]) == np.int64:
            self.attributes[k] = int(self.attributes[k])

    attr = {
        "Type": self.name,
        "Training Duration": "{}s".format(self.train_duration),
        "GridSearch Duration": "{}s".format(self.gridsearch_duration),
        "Parameters": self.attributes,
        "Metrics": self.metrics,
    }

    str_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
    return str_out

def __repr__(self):

    attr = {
        "Type": self.name,
        "Training Duration": "{}s".format(self.train_duration),
        "GridSearch Duration": "{}s".format(self.gridsearch_duration),
        "Parameters": self.attributes,
        "Metrics": self.metrics,
    }

    repr_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
    return repr_out
```

**Why this is a good feature/enhancement**
This will allow users to visualize the results and metrics of their models.

**Additional context**
n/a

**Comment by Turtle24** [comment]
@skekre98 I'll take this up if you don't mind.

**Comment by skekre98** [comment]
> @skekre98 I'll take this up if you don't mind.

That would be great, thanks for seeing this feature end to end :)

FYI there have been some additions since your last PR so you may want to rebase with the upstream main branch
