### ISSUE TITLE
SimpleRegressor KeyError: 'poisson' when running boston dataset

### ISSUE THREAD

**Issue by Turtle24** [skekre98/simple_learn#53]
**Describe the bug**
KeyError: 'poisson' when running boston dataset with the SimpleRegressor. When testing the boston dataset with the SimpleRegressor there's a KeyError. Removing ```poisson```  from the "DecisionTreeRegressor" in the ```param_grid``` remedies the issue. I think #24 will fix this though? I'm also logging this so I can implement the ```__str__``` and ```__repr__``` methods in for the SimpleRegressor class in #52.

***Go to the python shell and run the following:***
from sklearn.datasets import load_boston
from simple_learn.regressors import SimpleRegressor
boston = load_boston()
true_x = boston.data
true_y = boston.target
clf = SimpleRegressor()
clf.fit(true_x, true_y)

**Expected behavior**
Expected the classifier to fit.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

```
>>> from sklearn.datasets import load_boston
>>> from simple_learn.regressors import SimpleRegressor
>>> boston = load_boston() 
>>> true_x = boston.data   
>>> true_y = boston.target 
>>> clf = SimpleRegressor()
>>> clf.fit(true_x, true_y)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\tree\_classes.py", line 1242, in fit
    super().fit(
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\tree\_classes.py", line 336, in fit
    criterion = CRITERIA_REG[self.criterion](self.n_outputs_,
KeyError: 'poisson'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aidan\simple_learn\simple_learn\regressors\simple_regressor.py", line 115, in fit
    grid_clf.fit(train_x, train_y)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\model_selection\_search.py", line 736, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\model_selection\_search.py", line 1188, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\model_selection\_search.py", line 708, in evaluate_candidates
```
When removing poisson from the DecisionTreeRegressor in param_grid. This is the output.

```
>>> from sklearn.datasets import load_boston
>>> from simple_learn.regressors import SimpleRegressor
>>> boston = load_boston() 
>>> true_x = boston.data   
>>> true_y = boston.target 
>>> clf = SimpleRegressor()
>>> clf.fit(true_x, true_y)
>>> clf
<simple_learn.regressors.simple_regressor.SimpleRegressor object at 0x000001E0145966A0>
>>> print(clf) 
{
    "Type": "GradientBoostingRegressor",
    "Training Duration": "0.019023418426513672s",
    "GridSearch Duration": "47.94800543785095s",
    "Parameters": {
        "criterion": "mse",
        "learning_rate": 0.1,
        "loss": "ls",
        "max_depth": 3,
        "max_features": "sqrt",
        "n_estimators": 50
    },
    "Metrics": {
        "Training Score": 4.627489012405178,
        "Mean Absolute Error": 1.6081269523286306,
        "Mean Square Error": 4.232804375535621,
        "R-Squared": 0.9498599072505728
    }
}
```

**Comment by skekre98** [comment]
Hi @Turtle24, good catch. Although it is not a complete error, this does point out the issue that the `try/except` block does not catch all errors.
https://github.com/skekre98/simple_learn/blob/39f1674ebee90f2bc5df36b4c933a2021addeae4/simple_learn/regressors/simple_regressor.py#L114-L119
I'd suggest using `BaseException` in the except statement: [docs](https://docs.python.org/3.5/library/exceptions.html#exception-hierarchy). It would end up looking something like this:
```python
try:
    # gridsearch
except BaseException as error:
    self.failed_models.append(model_name)
    self.logger.warning(f"{model_name} failed, Error : {error}")
    continue
```

We would like to let users know that a certain model has failed and why because it would let them know more about their data. This way we don't have to remove poisson from the `param_grid` and can leverage it to model other types of data. Would you be interested in taking up this issue?

**Comment by Turtle24** [comment]
That makes a lot sense @skekre98. Yeah I'll gladly take it on. I should be finished with #52 quite soon. So I'll be able to jump over to this. I just removed poisson so I could test the SimpleRegressor methods.

**Comment by skekre98** [comment]
> That makes a lot sense @skekre98. Yeah I'll gladly take it on. I should be finished with #52 quite soon. So I'll be able to jump over to this. I just removed poisson so I could test the SimpleRegressor methods.

Awesome, I'll go ahead and assign this over to you :)

**Comment by Turtle24** [comment]
@skekre98 I added the BaseException as you suggested and it seems to be working. What do you think?

```python
 try:
      grid_clf.fit(train_x, train_y)
except BaseException as error:
      self.failed_models.append(name)
      self.logger.warning(f"{name} failed, Error : {error}")
      continue
```
Poisson fails still but the next best model gets fitted.
```
>>> from sklearn.datasets import load_boston
>>> from simple_learn.regressors import SimpleRegressor
>>> boston = load_boston()
>>> true_x = boston.data
>>> true_y = boston.target
>>> clf = SimpleRegressor()
>>> clf.fit(true_x, true_y)
DecisionTreeRegressor failed, Error : 'poisson'
>>> clf
<simple_learn.regressors.simple_regressor.SimpleRegressor object at 0x0000022E4DF466A0>
>>> print(clf)
{
    "Type": "GradientBoostingRegressor",
    "Training Duration": "0.03603243827819824s",
    "GridSearch Duration": "46.36451077461243s",
    "Parameters": {
        "criterion": "mse",
        "learning_rate": 0.1,
        "loss": "ls",
        "max_depth": 3,
        "max_features": "sqrt",
        "n_estimators": 100
    },
    "Metrics": {
        "Training Score": 4.538821867258774,
        "Mean Absolute Error": 1.213331369076752,
        "Mean Square Error": 2.47434032484902,
        "R-Squared": 0.9706899628769452
    }
}
>>>
```

**Comment by skekre98** [comment]
> @skekre98 I added the BaseException as you suggested and it seems to be working. What do you think?
> 
> ```python
>  try:
>       grid_clf.fit(train_x, train_y)
> except BaseException as error:
>       self.failed_models.append(name)
>       self.logger.warning(f"{name} failed, Error : {error}")
>       continue
> ```
> 
> Poisson fails still but the next best model gets fitted.
> 
> ```
> >>> from sklearn.datasets import load_boston
> >>> from simple_learn.regressors import SimpleRegressor
> >>> boston = load_boston()
> >>> true_x = boston.data
> >>> true_y = boston.target
> >>> clf = SimpleRegressor()
> >>> clf.fit(true_x, true_y)
> DecisionTreeRegressor failed, Error : 'poisson'
> >>> clf
> <simple_learn.regressors.simple_regressor.SimpleRegressor object at 0x0000022E4DF466A0>
> >>> print(clf)
> {
>     "Type": "GradientBoostingRegressor",
>     "Training Duration": "0.03603243827819824s",
>     "GridSearch Duration": "46.36451077461243s",
>     "Parameters": {
>         "criterion": "mse",
>         "learning_rate": 0.1,
>         "loss": "ls",
>         "max_depth": 3,
>         "max_features": "sqrt",
>         "n_estimators": 100
>     },
>     "Metrics": {
>         "Training Score": 4.538821867258774,
>         "Mean Absolute Error": 1.213331369076752,
>         "Mean Square Error": 2.47434032484902,
>         "R-Squared": 0.9706899628769452
>     }
> }
> >>>
> ```

Awesome, looks good to me! On another note, shouldn't `>>> clf` be returning the same thing as `>>> print(clf)`?

**Comment by Turtle24** [comment]
@skekre98 The repo I did this on was a commit behind because of the PR not being merged yet so you're absolutely right. I'll double check it and make sure it's working as intended.
