### ISSUE TITLE
Progress updates for fit

### ISSUE THREAD

**Issue by Turtle24** [skekre98/simple_learn#58]
**Description of feature/enhancement**
When I was working with the boston test data I thought it would be neat to be able to see how the process is going time wise. Closest I've got is below but it's getting there. This is a nice to have but isn't the most pressing thing to have.

You can add an actual progress bar, so that's what I intend to do with the cycles etc. The library allows for simple bars like this 
           ```76%|████████████████████████        | 7568/10000 [00:33<00:10, 229.00it/s]``` which would be the aim.

**Description of implementation**
I feel like it could be much cleaner but this is how far I've gotten. If you think it's worth pursuing I can finish it up. For example this is from ```tqdm``` _: 0it [00:00, ?it/s]_ so it would be better to get it working than calculate the running time as I did. But I wanted to get a good example going. 

```python
with tqdm(grid_clf.fit(train_x, train_y)) as pbar:
        cycle += 1
        cycle_time += (time.time() - start)
        pbar.set_description("Processing  %d/11 cycles - time %f" % (cycle, cycle_time))
```

**Why this is a good feature/enhancement**
It would be nice to see what's going on behind the scenes, especially for larger datasets.

**Additional context**
```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> iris = load_iris()
>>> clf = SimpleClassifier()       
>>> clf.fit(iris.data, iris.target)
Processing  1/11 cycles - time 1.724612: : 0it [00:00, ?it/s]
Processing  2/11 cycles - time 1.753618: : 0it [00:00, ?it/s]
Processing  3/11 cycles - time 1.902152: : 0it [00:00, ?it/s]
Processing  4/11 cycles - time 1.978862: : 0it [00:00, ?it/s]
Processing  5/11 cycles - time 3.115685: : 0it [00:00, ?it/s]
Processing  6/11 cycles - time 9.910774: : 0it [00:00, ?it/s]
Processing  7/11 cycles - time 10.034952: : 0it [00:00, ?it/s]
Processing  8/11 cycles - time 10.067357: : 0it [00:00, ?it/s]
Processing  9/11 cycles - time 19.530142: : 0it [00:00, ?it/s]
Processing  10/11 cycles - time 19.563148: : 0it [00:00, ?it/s]
Processing  11/11 cycles - time 19.583149: : 0it [00:00, ?it/s]
>>>clf
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0010006427764892578s",
    "GridSearch Duration": "0.11702847480773926s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
>>>
```

**Comment by skekre98** [comment]
@Turtle24 this is an excellent idea! Definitely worth pursuing. Out of curiosity, what does the `: 0it [00:00, ?it/s]` at the end refer to?

**Comment by Turtle24** [comment]
> @Turtle24 this is an excellent idea! Definitely worth pursuing. Out of curiosity, what does the `: 0it [00:00, ?it/s]` at the end refer to?

@skekre98 Ok awesome😁. I think it's the default iteration/iterations, time and iteration per/second. I'm sure there's a better way to get the progress bar going though with ```tqdm```. We just need something to iterate through by the looks of it.

**Comment by Turtle24** [comment]
@skekre98 Ok so I think I've got it figured out. Tell me what you think. It doesn't affect the fit by the looks of it and it goes from 0-100 quite fluidly.

**Code used:**
```python
with tqdm(total=(len(model_param_map)), desc="Fitting Models", unit=" Cycle", ncols=100) as progressbar:
            estimators = all_estimators(type_filter="classifier")
            for name, ClassifierClass in (estimators):
            . . .
progressbar.update(1)
```

**What the output looks like::**
```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> iris = load_iris()
>>> clf = SimpleClassifier()       
>>> clf.fit(iris.data, iris.target)
Fitting Models: 100%|███████████████████████████████████████████| 11/11 [00:19<00:00,  1.81s/ Cycle]
>>> clf
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009999275207519531s",
    "GridSearch Duration": "0.12602949142456055s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
>>>
```

**Comment by skekre98** [comment]
@Turtle24 this is great! Feel free to open up a PR whenever you think it is ready :)
