### ISSUE TITLE
Add progress bar to SimpleRegressorList

### ISSUE THREAD

**Issue by skekre98** [skekre98/simple_learn#61]
**Description of feature/enhancement**
Need to add the progress bar we are using for SimpleModels to SimpleRegressorList

**Description of implementation**
For implementation see how progress bar is generated in `simple_learn/regressors/simple_regressor.py`

**Why this is a good feature/enhancement**
Will allow users to see how fitting operation is coming along.

**Additional context**
Code can be copied over from SimpleRegressor

**Comment by Turtle24** [comment]
Hey, it's been awhile. I'd like to take this one if it's up for grabs.

**Comment by skekre98** [comment]
> Hey, it's been awhile. I'd like to take this one if it's up for grabs.

Hi, that would be great. I'll go ahead and assign the issue over to you 👍
